# install.conf for OpenBSD autoinstall
Choose your keyboard layout = us
System hostname = myhost
Network interface to configure = vio0
IPv4 address for vio0 = autoconf
IPv6 address for vio0 = autoconf
Network interface to configure = done
Password for root account = root-access-please
Start sshd(8) by default = yes
Do you expect to run the X Window System = no
Change the default console to com0 = no
Setup a user = no
Allow root ssh login = yes
What timezone are you in = Australia/Perth
Which disk is the root disk = sd0
Encrypt the root disk with a (p)assphrase or (k)eydisk = no
Use (W)hole disk MBR, whole disk (G)PT or (E)dit = W
Use (A)uto layout, (E)dit auto layout, or create (C)ustom layout = a
Location of sets = cd0
Set name(s) = -x*
Directory does not contain SHA256.sig. Continue without verification = yes
