#!/usr/bin/env bash

set -e

print_help() {
    echo "Install latest version of spire. Installation directory defaults to /usr/local/bin."
    echo -e
    echo "Usage:"
    echo "$0 [INSTALL_DIR]"
    exit 1
}

DOWNLOAD_DIR="/tmp"
INSTALL_DIR="/usr/local/bin"

OPTS=${1:-}
if [ "$OPTS" ]; then
  if [ "$OPTS" == "-h" ] || [ "$OPTS" == "--help" ]; then
    print_help
  else
    INSTALL_DIR="$OPTS"
  fi
fi

echo -n "fetching release information... "
VERSION_RELEASED="$(curl -sL https://raw.githubusercontent.com/epiccastle/spire/master/.meta/VERSION_RELEASED)"
echo $VERSION_RELEASED

echo -n "detecting os... "
set +e
UNAME=$(uname -s)
if [ "$?" -eq 0 ]; then
  case "$UNAME" in
    Linux*)   PLATFORM=linux COMPRESSION=tgz;;
    FreeBSD*) PLATFORM=freebsd COMPRESSION=tgz;;
    Darwin*)  PLATFORM=macos COMPRESSION=zip;;
    *)        PLATFORM=unknown COMPRESSION=zip;;
  esac
else
  PLATFORM=windows COMPRESSION=zip
fi
set -e
echo $PLATFORM

case "$PLATFORM" in
  freebsd) echo "freebsd install not supported from installer script"; exit 1;;
  macos) echo "macos install not supported from installer script"; exit 1;;
  windows) echo "spire does not support windows clients (yet)"; exit 1;;
esac

DOWNLOAD_FILE="spire-${VERSION_RELEASED}-${PLATFORM}-amd64.${COMPRESSION}"
DOWNLOAD_URL="https://github.com/epiccastle/spire/releases/download/v${VERSION_RELEASED}/${DOWNLOAD_FILE}"

echo -n "downloading archive from $DOWNLOAD_URL... "

cd "$DOWNLOAD_DIR"
set +e
curl -o "$DOWNLOAD_FILE" --show-error -sfL "$DOWNLOAD_URL"
RESULT=$?
set -e
if [ "$RESULT" -ne 0 ]; then
  echo "failed!"
  exit 1
fi
echo "done"

echo -n "extracting binary... "
case "$COMPRESSION" in
  zip) unzip -qqo "$DOWNLOAD_FILE"; rm "$DOWNLOAD_FILE";;
  tgz) tar xvf "$DOWNLOAD_FILE"; rm "$DOWNLOAD_FILE";;
esac
echo "done"

while [ ! -w "$INSTALL_DIR" ]; do
  echo "Cannot write to $INSTALL_DIR. Insufficient privileges."

  echo -n "Enter new install path, or press return to su to root and install in $INSTALL_DIR: "
  read NEW_INSTALL_DIR
  if [ "$NEW_INSTALL_DIR" == "" ]; then
    echo "Enter root password to install"
    su -c 'mv -f "$INSTALL_DIR/spire" "$INSTALL_DIR/spire.old"; mv -f "$DOWNLOAD_DIR/spire" "$INSTALL_DIR/spire"'
    echo "done"
    exit 0
  fi
  INSTALL_DIR="$NEW_INSTALL_DIR"
done

cd "$INSTALL_DIR"
if [ -f spire ]; then
  echo -n "Moving $INSTALL_DIR/spire to $INSTALL_DIR/spire.old ... "
  mv -f "$INSTALL_DIR/spire" "$INSTALL_DIR/spire.old"
  echo "done"
fi

echo -n "Installing spire to $INSTALL_DIR ... "
mv -f "$DOWNLOAD_DIR/spire" "$INSTALL_DIR/spire"
echo "done"
